#file generated by "Wave"-->SaveFormat
onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb/uut/unit_decode/RegisterFile/CLK
add wave -noupdate /tb/uut/unit_decode/RegisterFile/REGISTERS
add wave -noupdate /tb/uut/unit_memory/DRAM/DRAM_mem
add wave -noupdate /tb/uut/unit_control/FETCH_STALL
add wave -noupdate /tb/uut/unit_control/current_state
add wave -noupdate /tb/uut/unit_control/cw
add wave -noupdate /tb/uut/unit_control/cw_selected
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1224 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 253
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {124 ns}
